### ISSUE TITLE
旋轉和亞點數效果問題

### ISSUE THREAD

**Issue by Liao-lin** [DennisLiu1993/Fastest_Image_Pattern_Matching#1]
![image](https://user-images.githubusercontent.com/46985683/168514759-f8b1ac02-9328-4dfb-8bfc-f1b3dccd1a29.png)
你好,首先感謝分享，我在使用樣例圖片發現是不能識別旋轉和亞點數的，請問是什麼原因，沒有改動原始程式碼。 是哪裡還需要設定嗎

**Comment by DennisLiu1993** [comment]
@Liao-lin 
把Tolerance Angle設為180就可以了

**Comment by Liao-lin** [comment]
好的, 已經可以了 謝謝

**Comment by Liao-lin** [comment]
不是额外的，不知道什么原因，这台电脑视窗自己跳出来了，没有内嵌在里面

**Comment by DennisLiu1993** [comment]
那妳試試看能不能用滾輪縮放

另外，你是用OpenCV4以後的本版嗎?
如果可以的話用3.1版試試

**Comment by Liao-lin** [comment]
是用的opencv3. 4。 沒關係，不影響使用
