### ISSUE TITLE
SIMD加速处理

### ISSUE THREAD

**Issue by cheny00** [DennisLiu1993/Fastest_Image_Pattern_Matching#19]
謝謝回復。

第二個問題我看明白了，確實如你所說那樣。 

第三個問題你發的文章好像只是說NCC公式內部如何優化吧，似乎和亞圖元沒啥關係。

另外，在提速方面還是給個建議，你目前是在查找時取旋轉哪些範本，這個一般商務軟體都不是這樣弄得，都是提前做好個角度範本，然後查找時直接使用。畢竟這個演算法要有實際意義，速度是關鍵。

_Originally posted by @Imageshop in https://github.com/DennisLiu1993/Fastest_Image_Pattern_Matching/issues/2#issuecomment-1132358574_

*********************************************

您好，我看到了对MatchTemplate里的SIMD处理过程
查了一下现有的资料，没有找到合适的说明文档或是入门资料
对于SIMD技术的了解与研究，请问您有什么建议吗

**Comment by DennisLiu1993** [comment]
[Intel(R) Intrinsic Reference](https://www.intel.com/content/dam/develop/external/us/en/documents/18072-347603.pdf)
