### ISSUE TITLE
关于源码中，咨询功能作用

### ISSUE THREAD

**Issue by cheny00** [DennisLiu1993/Fastest_Image_Pattern_Matching#20]
博主，我又来请教了^v^
*********

1 FilterWithRotatedRect，进行重叠区域筛选
1.1 完全重合，为什么得分还会有不同的现象？

![image](https://user-images.githubusercontent.com/93637713/185591107-a9564a4f-25c4-41e0-af5c-08b524bc6b98.png)

1.2 计算交并比，为什么要对重叠区域的像素位置进行排序，才能计算该区域的轮廓面积？

![image](https://user-images.githubusercontent.com/93637713/185591319-4ce8bf21-06dd-4fd6-8769-ec9026cd50ca.png)

2 LearnPattern，进行图像模式训练
2.1.1 金字塔层数构建的依据是什么，MinReduceArea参数功能如何解读？
2.1.2 还有其他确定层数的机制方案吗？
(PS：记得以前见过一个金字塔层确定的公式，但忘了在哪了…)

![image](https://user-images.githubusercontent.com/93637713/185591451-599069b1-9715-4158-9aa1-24d26bcc7899.png)

2.2.1 处理的图像是灰度or多通道？
2.2.2 注意到界面(Read_TCHAR)加载时有灰度处理，但LearnPattern各层金字塔内处理均值、标准差时采用了Scalar定义的4通道，那这里的4通道指的什么参数运算？代表图像什么信息？

![image](https://user-images.githubusercontent.com/93637713/185591601-6b791f6b-3862-4a82-a538-60982af90fae.png)

![image](https://user-images.githubusercontent.com/93637713/185591975-f1388b4e-0506-49ff-91e7-42d49b7fdb11.png)

2.3.1 该模式训练是对检测图像各层金字塔的灰度信息进行处理吗？还是对模板图像进行处理？m_matSrc、m_matDst参数如何理解。
2.3.2 若是检测图像，相当于对初始状态的检测图像在各层金字塔上处理结果，为什么存储到“模板数据结构体”(s_TemplData)内？是我理解受对模板图像建立各旋转模型预处理的的缘故吗？那该如何理解s_TemplData的含义？

![image](https://user-images.githubusercontent.com/93637713/185592185-f02f7121-a8c8-479d-9f65-d0b6f6925506.png)

2.3.3 仅对检测/模板图像进行金字塔与灰处理，那如何与模板/检测图像计算灰度信息，进行匹配处理？是根据模板确定能识别的最小角度步长，旋转检测图像后进行分块匹配遍历筛选？

3 OnBnClickedButtonExecute，启动匹配过程
3.1 这里是进行检测图像批量测试吗？

![image](https://user-images.githubusercontent.com/93637713/185592481-c93af770-aefa-42f4-864d-e83ff832a673.png)

3.2 这里对X和Y进行排序的作用是什么？

![image](https://user-images.githubusercontent.com/93637713/185592684-08e32093-63f5-41da-92cc-3d7a177664f0.png)

4 match，关于亚像素实现
4.1 亚像素的初始定位参数是根据像素级定位结果确定？那亚像素处理是逐层(金字塔)处理(x,y,angle)参数，返还回像素级？还是在底层原图上根据像素级定位结果进行最后的亚像素处理？
4.2.1 if判断的含义作用是什么？后面的else看起来是逐层金字塔进行处理。
4.2.2 对像素级的匹配结果(x,y)进行的什么处理？对ptLT位置进行X2操作不理解。ptRotatePt2f变换作用是什么？ 

![image](https://user-images.githubusercontent.com/93637713/185593155-5e0b2d1f-001e-4849-b37d-d6e7d7d22b83.png)

5 相关函数功能作用
5.1 OutputRoi的作用是什么？显示匹配到的目标结果？

![image](https://user-images.githubusercontent.com/93637713/185593254-6290fc67-685b-482c-9ce0-2f51af302b87.png)

5.2 CCOEFF_Denominator相似度系数的分母计算，是哪有公式或说明吗？变换过程没看懂。另外，没有当前方案没有进行归一化吗？还是在哪个位置希望您能指出一下。

5.3 GetBestRotationSize是获得最佳目标尺寸参数吗？

5.4 GetNextMaxLoc，考虑到遮挡；多目标过程，将确定的结果进行黑色填充，是避免重复拾取吗？那相当于每次结果都是重复遍历一次检测图像？

**Comment by DennisLiu1993** [comment]
1.1 因為是來自不同旋轉角Source的比對結果
1.2 把多邊形的各端點連到中心，切成三角形計算面積，端點不排序無法切

2.1 等你查到再跟我說，有幾家庫是這樣用的
2.2.1 我是限制在單通道，cv::matchTemplate可以是多通道
2.2.2 meanStdDev ()可以輸入1~4通道影像，分別計算mean stdDev

2.3.1 對模板， m_matSrc=欲檢測圖像原尺寸, m_matDst=模板圖像原尺寸
2.3.2 參考[這篇](https://github.com/DennisLiu1993/Fastest_Image_Pattern_Matching/blob/main/Template%20Matching%20using%20Fast%20Normalized%20Cross%20Correlation.pdf)的公式
2.3.3 兩者都有進行金字塔/ 旋轉: 是的

3.1 是的，這段代碼可以達到這個效果
![image](https://github.com/DennisLiu1993/Fastest_Image_Pattern_Matching/blob/main/Manual%20Gif/NCCBasedOCR.gif)
3.2 為了把字元排序成由左到右上到下的順序

4.1 只有在原圖尺寸才會計算，其他層計算沒意義
4.2 iStopLayer是讓你可以改代碼使流程不跑完全部金字塔就結束(少一層大概快4倍)，這是早期這個演算法速度太慢時湊合用的，現在已經用不到了...

5.1 這個也不用理，只是讓你把比對區域輸入成圖像
5.2 同2.3.2，有規一化
5.3 黑框是原圖(Inspection Image)旋轉後，藍框是最佳搜尋尺寸 (原始的搜尋範圍是以求取黑框的最小外接正矩形，藍框可以比這縮小一些)
![image](https://user-images.githubusercontent.com/104763587/186346808-63473477-b1ec-4177-8440-74f2208abf16.png)
5.4 是的，求極值都是重新遍歷，所以才有之前跟你說的這個函數可以優化
但對於模板尺寸非常小的case才有用


我說老哥你也問太多了，幫我宣傳下

**Comment by cheny00** [comment]
没问题，肯定帮大哥宣传介绍的
(PS：最近刚接触这领域，相信以后认识的人就会多了；有啥需要我能帮的一定帮大哥)
******
2.2.2 灰度图像采用meanStdDev ()函数，实际仅用了第一通道进行mean和stdDev计算吧

2.2.3 我看到《机器视觉算法与应用》中对模板匹配介绍ncc匹配，是将模板在检测图像上逐像素进行遍历匹配和计算相似度，从而筛选出最佳(x,y)，您这里也是这个思路吗？

4.2 iStopLayer部分注释掉也不会影响整体运行效果吧

5.3 是对每次旋转后的检测图像，各自截取相应最小外接正方形吗？多余区域采用黑色填充吧。

5.4 shape匹配也是采用类似填充获取极值，实现多目标检测的吗？还是有其他思路完成多目标任务？

**Comment by DennisLiu1993** [comment]
2.2.2 是的，templMean[1]~templMean[3]都是0
2.2.3 是的，你看我貼的那兩篇論文就知道

4.2 沒錯
5.3 
![image](https://user-images.githubusercontent.com/104763587/186559068-dca2942e-fcaf-4b72-bcfb-bf314d69fba4.png)
用黑色區域沒錯，但沒有取外接正方形，概念直接把紅框的LeftTop點旋轉一個角度之後，用長寬取出一個區域，不過實作以warpAffine達成

5.4 多目標跟填充無關，的確是這個思路

**Comment by cheny00** [comment]
感谢回复

5.4 shape的多目标是如何避免重复定位相同目标呢

**Comment by DennisLiu1993** [comment]
我記得meiqua沒有特別去做多標靶判別，因為shape稍有一點偏差分數就會掉很多，跟NCC不一樣

**Comment by southmilkyway** [comment]
博主你好，想请教你一个问题，我打算用你的这个算法封装一个dll，想通过C#来调用，我把 CMatchToolDlg::LearnPattern（）和cmat.Match（）两个函数进行了封装，但是测试后发现匹配不了，
![屏幕截图 2022-09-14 203615](https://user-images.githubusercontent.com/108310938/190155357-05afa0a0-708d-45b0-8021-9215409e2bdb.png)
在这个位置就匹配不出来了，匹配分数为0，想请教一下你除了在这两个函数里边做事情之外，别的地方也有图像处理么？

**Comment by DennisLiu1993** [comment]
是包裝後就匹配不了還是包裝前
如果是包裝前傳個原圖來看看
如果是包裝後把dll設為起始專案就能進中斷點吧

**Comment by southmilkyway** [comment]
> 是包裝後就匹配不了還是包裝前 如果是包裝前傳個原圖來看看 如果是包裝後把dll設為起始專案就能進中斷點吧

用你的源码可以匹配的到，打包后就匹配不到了，我测试时用的dll源码跑的，直接可以打断点，问题应该就在我画红框这里，可能是我在哪里忽略了某个点，所以就想请教一下在这两个函数之外的地方有没有要注意的东西

**Comment by southmilkyway** [comment]
感谢回复！
用你的源码可以匹配的到，打包后就匹配不到了，我测试时用的dll源码跑的，直接可以打断点，问题应该就在我画红框这里，可能是我在哪里忽略了某个点，所以就想请教一下在这两个函数之外的地方有没有要注意的东西


---原始邮件---
发件人: "BoKuan ***@***.***&gt;
发送时间: 2022年9月14日(周三) 晚上9:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DennisLiu1993/Fastest_Image_Pattern_Matching] 关于源码中，咨询功能作用 (Issue #20)




 
是包裝後就匹配不了還是包裝前
 如果是包裝前傳個原圖來看看
 如果是包裝後把dll設為起始專案就能進中斷點吧

**Comment by southmilkyway** [comment]
> 是包裝後就匹配不了還是包裝前 如果是包裝前傳個原圖來看看 如果是包裝後把dll設為起始專案就能進中斷點吧

原因找到了，比较无语，我没有把图片转换成单通道的图像

**Comment by PureHing** [comment]
@southmilkyway 你好，可以分享一下你打包的C# dll吗

**Comment by DennisLiu1993** [comment]
> @southmilkyway 你好，可以分享一下你打包的C# dll吗

我這邊有做C++ regular dll，能夠給C#使用
有需要的話信箱詳談

**Comment by PureHing** [comment]
@DennisLiu-elogic 信箱是多少呢

**Comment by southmilkyway** [comment]
> @southmilkyway 你好，可以分享一下你打包的C# dll吗

可以的，但是博主这里有标准的，可能会更适合你

**Comment by PureHing** [comment]
> > @southmilkyway 你好，可以分享一下你打包的C# dll吗
> 
> 
> 
> 可以的，但是博主这里有标准的，可能会更适合你

@southmilkyway 可以邮件发我一下吗？非常感谢！xautzxc@126.com

**Comment by DennisLiu1993** [comment]
> @DennisLiu1993 信箱是多少呢

dennisliu1993@gmail.com
或wechat dennisliu1993

**Comment by ToNi981004** [comment]
> > @southmilkyway 你好，可以分享一下你打包的C# dll吗
> 
> 我這邊有做C++ regular dll，能夠給C#使用 有需要的話信箱詳談

Hi DennisLiu1993, have a nice day!
Can you send me your DLL?
My email: toni981004@gmail.com

**Comment by wangxiaoding0422** [comment]
> > @southmilkyway 你好，可以分享一下你打包的C# dll吗
> 
> 可以的，但是博主这里有标准的，可能会更适合你

我想试试C#的DLL作对比。可以分享一下你的DLL么？ 我的邮箱：wangxd0422@163.com 感谢！

**Comment by cheny00** [comment]
hi~博主，时隔这么久，我又重新研究了一下您的算法。有个疑惑仍然无法解释，前来寻求博主的指导。
在亚像素计算中，当未设置旋转角度时，获取的是未亚像素的数据；但设置旋转角度时，获取的是亚像素的数据。亚像素处理与是否选中“次像素估计”按键无关，即与如下SubPixEsimation()功能函数没关系，或是SubPixEsimation()功能在什么场景下可以产生效果呢？我理解的是金字塔上层与当前层具有相同旋转角度下均为最高得分时进行二次插值拟合，这样效果就比较有限。如何优化能对每个最佳的结果均进行有效的插值拟合呢？

SubPixEsimation()功能函数应用
![image](https://user-images.githubusercontent.com/93637713/217513800-4338b5fb-3146-4fdb-b0c6-2f43da993736.png)

无旋转角度，“次像素估计”按键未按下
![image](https://user-images.githubusercontent.com/93637713/217517277-905e70ad-66f3-406f-8b7a-962d4c0916c1.png)

无旋转角度，“次像素估计”按键按下
![image](https://user-images.githubusercontent.com/93637713/217517503-71cbef7a-a64e-4fcb-a496-12fc27d1ddc7.png)

有旋转角度，“次像素估计”按键未按下
![image](https://user-images.githubusercontent.com/93637713/217517789-044fbf93-50b0-45e8-962c-47dea12a0798.png)

有旋转角度，“次像素估计”按键按下
![image](https://user-images.githubusercontent.com/93637713/217518354-16e7ef96-1ddb-4dbb-8ce6-00ae90aa05c1.png)

**Comment by DennisLiu1993** [comment]
https://tw511.com/a/01/44138.html
這篇你可以看一下

三两白菜 ***@***.***> 於 2023年2月9日 週四 下午4:15寫道：

**Comment by cheny00** [comment]
谢谢博主的帮助
在插值方面，您是否尝试过其他插值拟合，进行对比二项式插值呢？
在原理或评测方面，对误差精度和耗时有什么见解呀。

**Comment by DennisLiu1993** [comment]
有個二次式曲線找頂點的 可以試試
