### ISSUE TITLE
这段为啥注释了

### ISSUE THREAD

**Issue by chen15861132927** [DennisLiu1993/Fastest_Image_Pattern_Matching#22]
https://github.com/DennisLiu1993/Fastest_Image_Pattern_Matching/blob/0ebfa3431627aa251f2ca2ae322f09291680775b/MatchTool/MatchToolDlg.cpp#L890

我试了一下这段放开时间会非常好，基本可以PK Halcon ，VisionPro.  这段注释有什么目的吗？

**Comment by DennisLiu1993** [comment]
這個函數在一般情況可以省一點時間，但遇到高重疊的目標就極容易誤刪候選
你可以試試這張
![2](https://user-images.githubusercontent.com/104763587/188579601-f04b45f4-2af3-436b-b2b0-3c7a996a0a49.jpg)

反正低層數的匹配速度很快，犧牲一點時間換準確度

**Comment by chen15861132927** [comment]
好的，我来试试你的图片.
![KeyLogicFormula](https://user-images.githubusercontent.com/1551647/188827391-9dfd65dd-de8c-4138-a953-cf63e762cc4c.png)
![KeyLogicFormula_0](https://user-images.githubusercontent.com/1551647/188829774-e84868d9-3ad8-4e28-b488-f6d3bcdfe2b5.png)
这是我对关键代码的理解，希望可以大家一起学习.
