### ISSUE TITLE
请教一下，轻微或者部分遮挡，如何拉低计算出来的阈值

### ISSUE THREAD

**Issue by PureHing** [DennisLiu1993/Fastest_Image_Pattern_Matching#27]
![image](https://user-images.githubusercontent.com/62579216/203772031-aa53700b-5956-41c1-bb0f-978e0c2998ae.jpeg)

比如这个把d遮住了，计算出来还有0.9，如何可以降低这个得分

**Comment by DennisLiu1993** [comment]
沒辦法 這就是NCC算出來的結果

**Comment by PureHing** [comment]
號的 謝謝
