### ISSUE TITLE
Support for installation

### ISSUE THREAD

**Issue by Haylemicheal** [DennisLiu1993/Fastest_Image_Pattern_Matching#29]
How can I install and use it in Linux Ubuntu 22.04?

**Comment by DennisLiu1993** [comment]
I think MFC framework is not supported in Ubuntu.
You can use QT to create window application, extract pure c++ code from this project and then compile with g++

**Comment by Haylemicheal** [comment]
Okay, What about using it in python?

**Comment by DennisLiu1993** [comment]
I can provide you with c++ dll for python on Windows System (charged)
You can also build this project to dll yourself, just use ctypes in python to send/get data from the dll

**Comment by Haylemicheal** [comment]
Thank you very much! It would be great if you provide me the dll file and if you show me sample code. Thanks again!

**Comment by DennisLiu1993** [comment]
It's a charged item, we can talk about details via email if you need it

**Comment by Haylemicheal** [comment]
okay good!
