### ISSUE TITLE
can't move any image to the program

### ISSUE THREAD

**Issue by udarrr** [DennisLiu1993/Fastest_Image_Pattern_Matching#41]
Hello
After building it's impossible move any image.
Src and dst image is 0x0

![issue](https://github.com/DennisLiu1993/Fastest_Image_Pattern_Matching/assets/77188735/daad63a5-0738-4170-981f-8613f99290ea)

![issue1](https://github.com/DennisLiu1993/Fastest_Image_Pattern_Matching/assets/77188735/01dcd1fa-4514-4b32-978b-5cf2c4f64f44)

**Comment by DennisLiu1993** [comment]
1. just use menu to load image because some OS version cannot trigger drop file event
2. make sure .Lang file is in the same dir as .exe

**Comment by udarrr** [comment]
Generally looke like because of version opencv 3 i've changed it to 4.1.x and everythings is fine.
