### ISSUE TITLE
关于加速

### ISSUE THREAD

**Issue by fcc315** [DennisLiu1993/Fastest_Image_Pattern_Matching#42]
Hi 您好

想请教一下加速的问题，和openmp相比较而言，simd的加速效果会更好吗？因我用meiqua 的template match, 虽然openmp提速1.5倍，但还是希望继续提速。现在想寻求simd的方法。

**Comment by DennisLiu1993** [comment]
主要是convolution的地方要加速,而用SIMD才能通用在所有ＣＰＵ,
其他小地方用無法用SIMD,反而是openmp比較適合

**Comment by fcc315** [comment]
> 主要是convolution的地方要加速,而用SIMD才能通用在所有ＣＰＵ, 其他小地方用無法用SIMD,反而是openmp比較適合

明白了，我没有在您的代码里看见SIMD的部分，是没有公开吗？我理解的opencv里面有内嵌的SIMD的支持，只要在项目中开启，但我自己在测试的时候，感觉开启关闭没有任何效果，迷茫

**Comment by DennisLiu1993** [comment]
代碼裡有的,搜尋MatchTemplate()
開了沒效果有幾個原因：
1.你的ＣＰＵ不支持ＳＳＥ
2. 編譯OpenCV源碼時沒有開啟ＳＳＥ選項

你想要加速的話可以嘗試用M2 CPU, 我用arm指令編譯後速度比原本的快了10倍,但不確定是M2的影像處理內核發揮效用還是Unix/Linux的原因

**Comment by fcc315** [comment]
好的，我检查一下，感谢！
