### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by suahelen** [DennisLiu1993/Fastest_Image_Pattern_Matching#44]
Hi Dennis, 

I really like what you did with this piece of code here. With some modification I got this to run for my application quite nicely. However, the code itself is hardly usable as it is all put into the mainform in one class. 

Would you be interested to release a version of the code where the actual processing part is separated better from the form itself? I think this would increase the usability of your repository by quite a bit. 
If you would want any help I would gladly assist you with that work as I have done it to some extent already.
Let me know if you are interested. 

Cheers

**Comment by DennisLiu1993** [comment]
Hi, suahelen, 
Actually I have already extracted a match class separated from MFC class (pure C++), which makes it be able to compile on other platforms like Unix and Linux and usable for python import, but it's for personal usage.

Appreciate your effor!

**Comment by suahelen** [comment]
Well that's unfortunate to hear, but I do understand your reasoning. 

Anyways, thanks for your work.
