### ISSUE TITLE
指定旋转范围时 阈值 没达到1.0

### ISSUE THREAD

**Issue by ershat-dl** [DennisLiu1993/Fastest_Image_Pattern_Matching#45]
我试图修改旋转范围， 并且分别得到了不同的结果

旋转角度为 0
![image](https://github.com/DennisLiu1993/Fastest_Image_Pattern_Matching/assets/79347883/8c5e853c-c8c6-4693-822b-288d006414fa)

更改旋转范围时
![image](https://github.com/DennisLiu1993/Fastest_Image_Pattern_Matching/assets/79347883/b8dbda5f-4620-4f8a-8b32-423ef83eb2b9)

问题出现在这个代码
```
if (vecNewMatchParameter[j].dMatchScore > dBigValue)
        {
	        iMaxScoreIndex = j;
	        dBigValue = vecNewMatchParameter[j].dMatchScore;
        }
```

看了一下代码， 分别计算 金字塔第二层 和 第三层 时 对应的角度和阈值如下：

第二层
```
angle step = 4
-4  -- 0.94
 0  -- 0.96 
 4  -- 0.98
```
这个时候 自然会选择 第三个结果 ` 4°` `0.98`, 然后进入第三层计算

第三层
```
angle step = 2
2  -- 0.98
4  -- 0.94 
6  -- 0.90
```

就这样 漏掉了 角度为 0 的 最佳结果， 不知道 第二层 4° 的结果 为什么 会比 0° 高一些。 但是第三层 0° 的阈值 是 1.0

**Comment by DennisLiu1993** [comment]
確實，可以把+-一個step的地方改成+-兩個step，應該可以改善，不過多花時間
